/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct num {
	float a;
	float b;
};
typedef struct num num;

#define MATH_PROGRAM 9999999
#define ADD_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  float * add_1(num *, CLIENT *);
extern  float * add_1_svc(num *, struct svc_req *);
extern int math_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  float * add_1();
extern  float * add_1_svc();
extern int math_program_1_freeresult ();
#endif /* K&R C */
#define SUB_VERSION 2

#if defined(__STDC__) || defined(__cplusplus)
#define sub 2
extern  float * sub_2(num *, CLIENT *);
extern  float * sub_2_svc(num *, struct svc_req *);
extern int math_program_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sub 2
extern  float * sub_2();
extern  float * sub_2_svc();
extern int math_program_2_freeresult ();
#endif /* K&R C */
#define DIV_VERSION 3

#if defined(__STDC__) || defined(__cplusplus)
#define div 3
extern  float * div_3(num *, CLIENT *);
extern  float * div_3_svc(num *, struct svc_req *);
extern int math_program_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define div 3
extern  float * div_3();
extern  float * div_3_svc();
extern int math_program_3_freeresult ();
#endif /* K&R C */
#define MULT_VERSION 4

#if defined(__STDC__) || defined(__cplusplus)
#define mult 4
extern  float * mult_4(num *, CLIENT *);
extern  float * mult_4_svc(num *, struct svc_req *);
extern int math_program_4_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define mult 4
extern  float * mult_4();
extern  float * mult_4_svc();
extern int math_program_4_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_num (XDR *, num*);

#else /* K&R C */
extern bool_t xdr_num ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
