/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <string.h>

void
math_program_1(char *host, float n1, float n2)
{
	CLIENT *clnt;
	float  *result_1;
	num  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MATH_PROGRAM, ADD_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    add_1_arg.a = n1;
    add_1_arg.b = n2;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    else {
      printf("Result: %f\n", *result_1);
    }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
math_program_2(char *host, float n1, float n2)
{
	CLIENT *clnt;
	float  *result_1;
	num  sub_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MATH_PROGRAM, SUB_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    sub_2_arg.a = n1;
    sub_2_arg.b = n2;

	result_1 = sub_2(&sub_2_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    else {
      printf("Result: %f\n", *result_1);
    }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
math_program_3(char *host, float n1, float n2)
{
	CLIENT *clnt;
	float  *result_1;
	num  div_3_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MATH_PROGRAM, DIV_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    div_3_arg.a = n1;
    div_3_arg.b = n2;

	result_1 = div_3(&div_3_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    else {
      printf("Result: %f\n", *result_1);
    }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void
math_program_4(char *host, float n1, float n2)
{
	CLIENT *clnt;
	float  *result_1;
	num  mult_4_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MATH_PROGRAM, MULT_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
    mult_4_arg.a = n1;
    mult_4_arg.b = n2;

	result_1 = mult_4(&mult_4_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    else {
      printf("Result: %f\n", *result_1);
    }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
    float result;
    float num1, num2;
    char *mathop;
	if (argc < 5) {
        printf("Available math operations: ADD, SUB, DIV and MULT\n");
		printf("Usage: %s server_host MATHOP num1 num2\n", argv[0]);
		exit (1);
	}
	host = argv[1];
    mathop = argv[2];
    num1 = atof(argv[3]);
    num2 = atof(argv[4]);

    if(strcmp(mathop, "ADD") == 0)
      {
        math_program_1(host, num1, num2); // ADD        
      }
    if(strcmp(mathop, "SUB") == 0)
      {
        math_program_2(host, num1, num2); // SUB
      }
    if(strcmp(mathop, "DIV") == 0)
      {
        math_program_3(host, num1, num2); // DIV
      }
    if(strcmp(mathop, "MULT") == 0)
      {
        math_program_4(host, num1, num2); // MULT
      }
exit (0);
}
